apiVersion: v1
kind: Pod
metadata:
  name: myapp-prod
  labels:
    app: myapp
    type: front-end
  
spec:
  containers:
  - name: nginx-container
    image: nginx
    resources:
      requests:
        cpu: 200m
        memory: 128Mi
      
      limits:
        cpu: 250m
        memory: 256Mi

    ports:
    - containerPort: 80